name: eq_api_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.7.0

resolution: workspace

dev_dependencies:
  altive_lints: ^1.19.1
  eqmonitor_lints:
    git:
      url: https://github.com/YumNumm/EQMonitor
      ref: develop
      path: packages/eqmonitor_lints
